# Generated by Django 3.1.7 on 2021-03-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPosts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
